/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inventory;

import com.sql.InventoryDAO;
import com.sql.model.InventoryModel;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arjun.n
 */
public class InventoryForm extends javax.swing.JFrame {

    ArrayList<InventoryModel> existingInventory;
    /**
     * Creates new form InventoryForm
     */
    public InventoryForm() {
        initComponents();
        loadTableWithData();
        jTextField_Code.requestFocus();
    }
    
    private void loadTableWithData(){
        InventoryDAO inventory = new InventoryDAO();
        existingInventory = inventory.getAllDetails();
        removeTableEntries();
        DefaultTableModel model = (DefaultTableModel) jTable_Inventory.getModel();
        for(int i=0 ; i< existingInventory.size() ; i++){
            InventoryModel row = existingInventory.get(i);
            model.addRow(new Object[]{row.getItem_no(),row.getDetails(), row.getQuantity(), row.getHsnID(), row.getTax(), row.getCompany()});
        }
    }

    public boolean validateBillPage() {
        if (jTextField_Code.getText().isEmpty()
                || jTextField_Details.getText().isEmpty() || jTextField_Company.getText().isEmpty() 
                || jTextField_Quantity.getText().isEmpty()) {
            return false;
        } else {
            return true;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Details = new javax.swing.JLabel();
        jTextField_Details = new javax.swing.JTextField();
        jLabel_Quantity = new javax.swing.JLabel();
        jTextField_Quantity = new javax.swing.JTextField();
        jLabel_HSN = new javax.swing.JLabel();
        jTextField_HSN = new javax.swing.JTextField();
        jLabel_Code = new javax.swing.JLabel();
        jTextField_Code = new javax.swing.JTextField();
        jLabel_tax = new javax.swing.JLabel();
        jTextField_Tax = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Company = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton_Add = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Inventory = new javax.swing.JTable();
        jLabel_NotificationMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_Details.setText("Details");

        jLabel_Quantity.setText("Quantity");

        jLabel_HSN.setText("HSN");

        jLabel_Code.setText("Code");

        jLabel_tax.setText("TAX");

        jTextField_Tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TaxActionPerformed(evt);
            }
        });

        jLabel1.setText("COMPANY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Company, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Quantity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_HSN)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_HSN, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel_tax)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Tax, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(595, 595, 595))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_HSN)
                    .addComponent(jTextField_HSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_tax)
                    .addComponent(jTextField_Tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142))
        );

        jButton_Add.setText("Add");
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Delete.setText("Delete");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Delete)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Add)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Update)
                        .addComponent(jButton_Delete))))
        );

        jTable_Inventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Details", "Quantity", "HSN", "Tax", "Company"
            }
        ));
        jTable_Inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_InventoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Inventory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel_NotificationMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31))))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel_NotificationMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable_Inventory.getModel();
        String code = jTextField_Code.getText();
        String details = jTextField_Details.getText();
        String qty = jTextField_Quantity.getText();
        String hsn = jTextField_HSN.getText();
        String tax =jTextField_Tax.getText();
       
        if(!validateBillPage()){
            jLabel_NotificationMessage.setText("Please provide ItemCode,Details,Company & Quantity");
        }
        
        InventoryDAO inventory = new InventoryDAO();
        if(inventory.getDetailsFromItemNo(code) == null){
            InventoryModel detail = new InventoryModel();
            detail.setItem_no(jTextField_Code.getText());
            detail.setDetails(jTextField_Details.getText());
            detail.setCompany(jTextField_Company.getText());
            detail.setQuantity(Double.parseDouble(jTextField_Quantity.getText()));
            
            if(jTextField_Tax.getText().equals(null) || jTextField_Tax.getText().isEmpty()){
                 detail.setTax(0.0);
            }else{
                 detail.setTax(Double.parseDouble(jTextField_Tax.getText()));
            }
           
            if(jTextField_HSN.getText().equals(null) || jTextField_HSN.getText().isEmpty()){
                detail.setHsnID(0);
            }else{
                detail.setHsnID(Integer.parseInt(jTextField_HSN.getText()));
            }
           
            detail.setCostPrice(0);
            detail.setSalePrice(0);
            detail.setLocation(" ");
            detail.setItemNotes("");
            detail.setRegister_date(inventory.getCurrentDatetime());
            
            inventory.insertIntoInventory(detail);
            jLabel_NotificationMessage.setText("Item Added to Inventory" +code);
            loadTableWithData();
            
        }else{
            jLabel_NotificationMessage.setText("ItemCode Already Exist");
            jTextField_Details.setText(details);
            jTextField_Quantity.setText(qty);
            jTextField_HSN.setText(hsn);
            jTextField_Tax.setText(tax);
        }
        
    }//GEN-LAST:event_jButton_AddActionPerformed

    public void removeTableEntries(){
       DefaultTableModel model = (DefaultTableModel)jTable_Inventory.getModel();

        while(model.getRowCount() > 0){
            for(int i = 0 ; i < model.getRowCount();i++){
                 model.removeRow(i);
            }
        }
    }
    
    private void jTable_InventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_InventoryMouseClicked
        // TODO add your handling code here:
       DefaultTableModel model = (DefaultTableModel) jTable_Inventory.getModel();
       jTextField_Code.setText(model.getValueAt(jTable_Inventory.getSelectedRow(), 0).toString());
       jTextField_Details.setText(model.getValueAt(jTable_Inventory.getSelectedRow(), 1).toString());
       jTextField_Quantity.setText(model.getValueAt(jTable_Inventory.getSelectedRow(), 2).toString());
       jTextField_HSN.setText(model.getValueAt(jTable_Inventory.getSelectedRow(), 3).toString());
       jTextField_Tax.setText(model.getValueAt(jTable_Inventory.getSelectedRow(), 4).toString());
       jTextField_Company.setText(model.getValueAt(jTable_Inventory.getSelectedRow(), 5).toString());
       jTextField_Quantity.requestFocus();
    }//GEN-LAST:event_jTable_InventoryMouseClicked

    private void jTextField_TaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TaxActionPerformed

    public void makeFieldsEmpty(){
        jTextField_Code.setText(null);
        jTextField_Details.setText(null);
        jTextField_Company.setText(null);
        jTextField_Quantity.setText(null);
        jTextField_HSN.setText(null);
        jTextField_Tax.setText(null);
    }
    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        // TODO add your handling code here:
        
        if(!validateBillPage()){
            jLabel_NotificationMessage.setText("Please provide ItemCode,Details,Company & Quantity");
        }
        
        InventoryDAO inventory = new InventoryDAO();

        InventoryModel detail = new InventoryModel();
        detail.setItem_no(jTextField_Code.getText());
        detail.setDetails(jTextField_Details.getText());
        detail.setCompany(jTextField_Company.getText());
        detail.setQuantity(Double.parseDouble(jTextField_Quantity.getText()));

        if (jTextField_Tax.getText().equals(null) || jTextField_Tax.getText().isEmpty()) {
            detail.setTax(0.0);
        } else {
            detail.setTax(Double.parseDouble(jTextField_Tax.getText()));
        }

        if (jTextField_HSN.getText().equals(null) || jTextField_HSN.getText().isEmpty()) {
            detail.setHsnID(0);
        } else {
            detail.setHsnID(Integer.parseInt(jTextField_HSN.getText()));
        }

        detail.setCostPrice(0);
        detail.setSalePrice(0);
        detail.setLocation(" ");
        detail.setItemNotes("");
        inventory.updateInventory(detail);
        jLabel_NotificationMessage.setText("Item updated to Inventory");
        loadTableWithData();
        makeFieldsEmpty();
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Code;
    private javax.swing.JLabel jLabel_Details;
    private javax.swing.JLabel jLabel_HSN;
    private javax.swing.JLabel jLabel_NotificationMessage;
    private javax.swing.JLabel jLabel_Quantity;
    private javax.swing.JLabel jLabel_tax;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Inventory;
    private javax.swing.JTextField jTextField_Code;
    private javax.swing.JTextField jTextField_Company;
    private javax.swing.JTextField jTextField_Details;
    private javax.swing.JTextField jTextField_HSN;
    private javax.swing.JTextField jTextField_Quantity;
    private javax.swing.JTextField jTextField_Tax;
    // End of variables declaration//GEN-END:variables
}
